name       : haskell-x11-xft
version    : 0.3.1
release    : 3
source     :
    - https://hackage.haskell.org/package/X11-xft-0.3.1/X11-xft-0.3.1.tar.gz : 4eba3fee62570e06447654030a62fb55f19587884bc2cef77a9c3b2c3458f8d1
license    : LGPL-2.1-only
component  : programming.haskell
summary    : Bindings to the Xft, X Free Type interface library, and some Xrender parts
description: |
    Bindings to the Xft, X Free Type interface library, and some Xrender parts
builddeps  :
    - pkgconfig(xft)
    - pkgconfig(xrender)
    - haskell-cabal-install
    - haskell-data-default-class-devel
    - haskell-utf8-string-devel
    - haskell-x11-devel
rundeps    :
    - devel:
        - haskell-data-default-class-devel
        - haskell-utf8-string-devel
        - haskell-x11-devel
        - libxrender-devel
        - libxft-devel
optimize   : no-symbolic
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
