name       : haskell-x11-xft
version    : 0.3.4
release    : 4
source     :
    - https://hackage.haskell.org/package/X11-xft-0.3.4/X11-xft-0.3.4.tar.gz : 6200d2deabe9638bad4d1fed4399e3147254c2776a0fae71bf38ca423242a916
license    : LGPL-2.1-only
component  : programming.haskell
summary    : Bindings to the Xft, X Free Type interface library, and some Xrender parts
description: |
    Bindings to the Xft, X Free Type interface library, and some Xrender parts
builddeps  :
    - pkgconfig(xft)
    - pkgconfig(xrender)
    - ghc-devel
    - haskell-data-default-class-devel
    - haskell-utf8-string-devel
    - haskell-x11-devel
rundeps    :
    - devel :
        - haskell-data-default-class-devel
        - haskell-utf8-string-devel
        - haskell-x11-devel
        - libxrender-devel
        - libxft-devel
environment: |
    export LDFLAGS="${LDFLAGS/-Wl,-Bsymbolic-functions/-Wl,-Bsymbolic}"
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
